using System;
using Cognexalgo.Core.Models;

namespace Cognexalgo.Core.Models
{
    /// <summary>
    /// Represents a single buy or sell order generated by the VCP strategy.
    /// Carries all parameters required by <c>IOrderManagementService</c> to route
    /// the order to the correct broker (paper or live).
    /// </summary>
    public class VCPOrder
    {
        /// <summary>The signal that originated this order.</summary>
        public Guid SignalId { get; init; }

        /// <summary>Underlying equity or index symbol (e.g. "NIFTY").</summary>
        public string Symbol { get; init; } = string.Empty;

        /// <summary>Exchange trading symbol for the specific options contract (e.g. "22050 CE").</summary>
        public string TradingSymbol { get; init; } = string.Empty;

        /// <summary>"BUY" for entry; "SELL" for exit or partial exit.</summary>
        public string TransactionType { get; init; } = "BUY";

        /// <summary>Total number of units (lots × lotSize).</summary>
        public int Quantity { get; init; }

        /// <summary>Limit price; 0 for a pure market order.</summary>
        public decimal Price { get; init; }

        /// <summary>"MARKET" or "LIMIT".</summary>
        public string OrderType { get; init; } = "MARKET";

        /// <summary>Routing mode — paper or live.</summary>
        public VCPTradingMode Mode { get; init; }
    }
}
