using System;
using Cognexalgo.Core.Domain.Patterns;

namespace Cognexalgo.Core.Models
{
    /// <summary>
    /// A tradeable signal derived from a confirmed VCP pattern.
    /// Contains all entry, exit, and options-routing parameters required
    /// to place and manage the trade.
    /// </summary>
    public class VCPSignal
    {
        /// <summary>
        /// Unique identifier for this signal instance.
        /// </summary>
        public Guid Id { get; init; } = Guid.NewGuid();

        /// <summary>
        /// The VCP pattern that generated this signal.
        /// </summary>
        public VCPPattern Pattern { get; init; } = new();

        /// <summary>
        /// The recommended entry price (typically the pivot breakout level + a small buffer).
        /// </summary>
        public decimal EntryPrice { get; init; }

        /// <summary>
        /// The initial stop-loss price, placed below the tight low of the final contraction.
        /// </summary>
        public decimal StopLoss { get; init; }

        /// <summary>
        /// First profit target price (partial exit or 1:1 R level).
        /// </summary>
        public decimal Target1 { get; init; }

        /// <summary>
        /// Second profit target price (full exit or trailing activation level).
        /// </summary>
        public decimal Target2 { get; init; }

        /// <summary>
        /// The suggested options strike and type to trade the signal (e.g. "22200 CE").
        /// Empty string when no options leg is applicable.
        /// </summary>
        public string SuggestedStrike { get; init; } = string.Empty;

        /// <summary>
        /// The suggested options expiry series (e.g. "27-Mar-2025" or "Weekly").
        /// Empty string when no options leg is applicable.
        /// </summary>
        public string SuggestedExpiry { get; init; } = string.Empty;

        /// <summary>
        /// Risk-to-reward ratio computed as (Target1 − EntryPrice) / (EntryPrice − StopLoss).
        /// </summary>
        public decimal RiskRewardRatio { get; init; }

        /// <summary>
        /// The timestamp when this signal was generated by the scanner.
        /// </summary>
        public DateTime SignalTime { get; init; }

        /// <summary>
        /// Whether this signal is still open and eligible for entry or management.
        /// Set to <c>false</c> once the signal is filled, expired, or cancelled.
        /// </summary>
        public bool IsActive { get; init; }

        /// <summary>
        /// A one-line human-readable summary of the signal, suitable for Telegram notifications
        /// or dashboard tooltips.
        /// Format: "{Symbol} VCP {Quality} | Entry ₹{EntryPrice} SL ₹{StopLoss} T1 ₹{Target1} RR {RiskRewardRatio:F2}x"
        /// Returns an empty string if Pattern is null.
        /// </summary>
        public string SignalSummary =>
            Pattern is null
                ? string.Empty
                : $"{Pattern.Symbol} VCP {Pattern.Quality} | " +
                  $"Entry ₹{EntryPrice:N2}  SL ₹{StopLoss:N2}  T1 ₹{Target1:N2}  RR {RiskRewardRatio:F2}x";
    }
}
