CREATE TABLE "BrokerCredentials" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BrokerName" character varying(30) NOT NULL,
    "EncryptedApiKey" character varying(500),
    "EncryptedClientCode" character varying(500),
    "EncryptedPassword" character varying(500),
    "EncryptedTotpKey" character varying(500),
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BrokerCredentials" PRIMARY KEY ("Id")
);


CREATE TABLE "Candles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Symbol" character varying(50) NOT NULL,
    "TimeFrame" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Open" numeric NOT NULL,
    "High" numeric NOT NULL,
    "Low" numeric NOT NULL,
    "Close" numeric NOT NULL,
    "Volume" bigint NOT NULL,
    CONSTRAINT "PK_Candles" PRIMARY KEY ("Id")
);


CREATE TABLE "DailyPnlSummaries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    "StrategyId" character varying(25) NOT NULL,
    "TotalPnl" numeric NOT NULL,
    "TotalTrades" integer NOT NULL,
    "WinCount" integer NOT NULL,
    "LossCount" integer NOT NULL,
    "MaxDrawdown" numeric NOT NULL,
    "TradingMode" text NOT NULL,
    CONSTRAINT "PK_DailyPnlSummaries" PRIMARY KEY ("Id")
);


CREATE TABLE "EventLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Level" character varying(10) NOT NULL,
    "StrategyId" character varying(25),
    "Message" character varying(2000) NOT NULL,
    "Properties" jsonb,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EventLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "InstrumentMasters" (
    "Token" character varying(20) NOT NULL,
    "Symbol" character varying(60) NOT NULL,
    "Name" character varying(100),
    "Exchange" character varying(10) NOT NULL,
    "InstrumentType" text NOT NULL,
    "LotSize" integer NOT NULL,
    "TickSize" numeric NOT NULL,
    "StrikePrice" numeric NOT NULL,
    "Expiry" timestamp with time zone,
    "OptionType" character varying(5),
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InstrumentMasters" PRIMARY KEY ("Token")
);


CREATE TABLE "RmsLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StrategyId" character varying(25),
    "RuleType" text NOT NULL,
    "BreachValue" numeric NOT NULL,
    "ThresholdValue" numeric NOT NULL,
    "Action" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RmsLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "Strategies" (
    "StrategyId" character varying(25) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Type" text NOT NULL,
    "Status" text NOT NULL,
    "TradingMode" text NOT NULL,
    "UnderlyingSymbol" character varying(20) NOT NULL,
    "SignalConfigJson" jsonb,
    "RmsConfigJson" jsonb,
    "ExecutionConfigJson" jsonb,
    "MetricsJson" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone,
    "EndedAt" timestamp with time zone,
    "CreatedBy" character varying(50),
    "IsTemplate" boolean NOT NULL,
    "StateMachineSnapshot" jsonb,
    CONSTRAINT "PK_Strategies" PRIMARY KEY ("StrategyId")
);


CREATE TABLE "Ticks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Symbol" character varying(50) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Ltp" numeric NOT NULL,
    "Volume" bigint NOT NULL,
    "OpenInterest" bigint NOT NULL,
    CONSTRAINT "PK_Ticks" PRIMARY KEY ("Id")
);


CREATE TABLE "Signals" (
    "SignalId" character varying(40) NOT NULL,
    "StrategyId" character varying(25) NOT NULL,
    "LegId" character varying(35),
    "SignalType" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "TriggerCondition" character varying(500) NOT NULL,
    "IndicatorSnapshot" jsonb,
    "ActionTaken" text NOT NULL,
    "OrderId" character varying(60),
    "Symbol" character varying(50),
    "Price" double precision NOT NULL,
    "Reason" character varying(200),
    CONSTRAINT "PK_Signals" PRIMARY KEY ("SignalId"),
    CONSTRAINT "FK_Signals_Strategies_StrategyId" FOREIGN KEY ("StrategyId") REFERENCES "Strategies" ("StrategyId") ON DELETE RESTRICT
);


CREATE TABLE "StrategyLegs" (
    "LegId" character varying(35) NOT NULL,
    "StrategyId" character varying(25) NOT NULL,
    "LegNumber" integer NOT NULL,
    "TradingSymbol" character varying(50) NOT NULL,
    "SymbolToken" character varying(20),
    "Exchange" character varying(10) NOT NULL,
    "InstrumentType" text NOT NULL,
    "OptionType" character varying(5) NOT NULL,
    "StrikePrice" numeric NOT NULL,
    "Expiry" timestamp with time zone,
    "Direction" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Lots" integer NOT NULL,
    "Status" text NOT NULL,
    "EntryPrice" numeric NOT NULL,
    "ExitPrice" numeric NOT NULL,
    "EntryTime" timestamp with time zone,
    "ExitTime" timestamp with time zone,
    "StopLossPrice" numeric NOT NULL,
    "TargetPrice" numeric NOT NULL,
    "TrailingStopLoss" numeric NOT NULL,
    "Pnl" numeric NOT NULL,
    "ExitReason" integer,
    CONSTRAINT "PK_StrategyLegs" PRIMARY KEY ("LegId"),
    CONSTRAINT "FK_StrategyLegs_Strategies_StrategyId" FOREIGN KEY ("StrategyId") REFERENCES "Strategies" ("StrategyId") ON DELETE CASCADE
);


CREATE TABLE "Trades" (
    "TradeId" character varying(40) NOT NULL,
    "StrategyId" character varying(25) NOT NULL,
    "LegId" character varying(35),
    "Symbol" character varying(50) NOT NULL,
    "Direction" text NOT NULL,
    "Quantity" integer NOT NULL,
    "EntryPrice" numeric NOT NULL,
    "ExitPrice" numeric NOT NULL,
    "GrossPnl" numeric NOT NULL,
    "Charges" numeric NOT NULL,
    "NetPnl" numeric NOT NULL,
    "EntryTime" timestamp with time zone NOT NULL,
    "ExitTime" timestamp with time zone,
    "TradingMode" text NOT NULL,
    CONSTRAINT "PK_Trades" PRIMARY KEY ("TradeId"),
    CONSTRAINT "FK_Trades_Strategies_StrategyId" FOREIGN KEY ("StrategyId") REFERENCES "Strategies" ("StrategyId") ON DELETE RESTRICT
);


CREATE TABLE "Orders" (
    "OrderId" character varying(60) NOT NULL,
    "BrokerOrderId" character varying(30),
    "StrategyId" character varying(25) NOT NULL,
    "LegId" character varying(35),
    "SignalId" character varying(40),
    "TradingSymbol" character varying(50) NOT NULL,
    "Exchange" character varying(10) NOT NULL,
    "InstrumentType" text NOT NULL,
    "Direction" text NOT NULL,
    "OrderType" text NOT NULL,
    "ProductType" text NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric NOT NULL,
    "TriggerPrice" numeric NOT NULL,
    "Status" text NOT NULL,
    "FilledPrice" numeric NOT NULL,
    "FilledQuantity" integer NOT NULL,
    "PendingQuantity" integer NOT NULL,
    "RejectedQuantity" integer NOT NULL,
    "RejectionReason" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "PlacedAt" timestamp with time zone,
    "FilledAt" timestamp with time zone,
    "LatencyMs" bigint NOT NULL,
    "TradingMode" text NOT NULL,
    "IsSimulated" boolean NOT NULL,
    "RetryCount" integer NOT NULL,
    "MaxRetries" integer NOT NULL,
    "LastError" character varying(500),
    "PotentialProfit" numeric NOT NULL,
    "ProtectedProfit" numeric NOT NULL,
    "ActualProfit" numeric NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_Orders_Strategies_StrategyId" FOREIGN KEY ("StrategyId") REFERENCES "Strategies" ("StrategyId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_StrategyLegs_LegId" FOREIGN KEY ("LegId") REFERENCES "StrategyLegs" ("LegId")
);


CREATE INDEX "IX_Candles_Symbol_TimeFrame_Timestamp" ON "Candles" ("Symbol", "TimeFrame", "Timestamp");


CREATE UNIQUE INDEX "IX_DailyPnlSummaries_Date_StrategyId" ON "DailyPnlSummaries" ("Date", "StrategyId");


CREATE INDEX "IX_InstrumentMasters_Exchange" ON "InstrumentMasters" ("Exchange");


CREATE INDEX "IX_InstrumentMasters_Expiry" ON "InstrumentMasters" ("Expiry");


CREATE INDEX "IX_InstrumentMasters_Symbol" ON "InstrumentMasters" ("Symbol");


CREATE INDEX "IX_Orders_BrokerOrderId" ON "Orders" ("BrokerOrderId");


CREATE INDEX "IX_Orders_CreatedAt" ON "Orders" ("CreatedAt");


CREATE INDEX "IX_Orders_LegId" ON "Orders" ("LegId");


CREATE INDEX "IX_Orders_Status" ON "Orders" ("Status");


CREATE INDEX "IX_Orders_StrategyId" ON "Orders" ("StrategyId");


CREATE INDEX "IX_Orders_TradingMode" ON "Orders" ("TradingMode");


CREATE INDEX "IX_Signals_StrategyId" ON "Signals" ("StrategyId");


CREATE INDEX "IX_Signals_Timestamp" ON "Signals" ("Timestamp");


CREATE INDEX "IX_Strategies_CreatedAt" ON "Strategies" ("CreatedAt");


CREATE INDEX "IX_Strategies_Status" ON "Strategies" ("Status");


CREATE INDEX "IX_Strategies_TradingMode" ON "Strategies" ("TradingMode");


CREATE INDEX "IX_StrategyLegs_Status" ON "StrategyLegs" ("Status");


CREATE INDEX "IX_StrategyLegs_StrategyId" ON "StrategyLegs" ("StrategyId");


CREATE INDEX "IX_Ticks_Symbol_Timestamp" ON "Ticks" ("Symbol", "Timestamp");


CREATE INDEX "IX_Trades_EntryTime" ON "Trades" ("EntryTime");


CREATE INDEX "IX_Trades_StrategyId" ON "Trades" ("StrategyId");


